<%

  user = ENV["RAILS_DB_USER"] || ENV["lando_database_creds_user"]
  pass = ENV["RAILS_DB_PASS"] || ENV["lando_database_creds_password"]
  host = ENV["RAILS_DB_HOST"] || ENV["lando_database_conn_host"] || "localhost"
  port = ENV["RAILS_DB_PORT"] || ENV["lando_database_conn_port"] || 5432
  db   = ENV["RAILS_DB_NAME"] || 'manifold_development'
  test_db   = ENV["RAILS_TEST_DB_NAME"] || 'manifold_test'

%>

common: &common
  adapter: postgresql
  host: <%= host %>
  encoding: unicode
  pool: 50
  port: <%= port %>
  username: <%= user %>
  database: <%= db %>
  password: "<%= pass %>"

production:
  <<: *common

demo:
  <<: *common

staging:
  <<: *common

development:
  <<: *common

test:
  <<: *common
  database: <%= test_db %><%= ENV["TEST_ENV_NUMBER"] %>
